# Netlify configuration file for Next.js
[build]
  # Build command with type checking
  command = "npm run build:netlify"
  
  # Directory to publish (Next.js default output)
  publish = ".next"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

# Essential Netlify plugin for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # News aggregator should not be indexed
    X-Robots-Tag = "noindex, nofollow, nosnippet, noarchive"

# Cache static assets
[[headers]]
  for = "/favicon.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security redirects (optional)
# Force HTTPS in production
[[redirects]]
  from = "http://newsy-news-aggregator.netlify.app/*"
  to = "https://newsy-news-aggregator.netlify.app/:splat"
  status = 301
  force = true